#!/bin/bash
set -o pipefail

function copy-ids() {
	echo '>>> ' Copying to $1
	if(ssh-copy-id $1 2>/dev/null); then
	echo '<<< ' Copying from $1
	ssh $1 'ssh-copy-id (echo $SSH_CONNECTION | cut -d" " -f1)' 2>/dev/null &
	fi
}

for i in $(cat hosts | cut -f1 | grep -ve '^#' -e '^$'); do
copy-ids $i &
done
