#!/bin/bash
mov() {
	sudo cp $1 /$1
}

mkdir -p ~/.ssh
mkdir -p ~/.config
mkdir -p ~/src/scripts
mkdir -p ~/tmp

mov home/jtreed/.ssh/config
mov home/jtreed/.profile
mov home/jtreed/.config/fish
mov home/jtreed/.config/i3
mov home/jtreed/.xinitrc
mov home/jtreed/src/scripts/screenshot
mov home/jtreed/src/profile
mov etc/i3status.conf
