#!/usr/bin/fish

for i in (find fs -type f | sed -r 's/^fs//');
set dname (dirname $i)
if [ ! -e $i ] || ! diff $i fs$i;
echo Copying $i
if [ ! -d "$dname" ];
echo Creating $dname
mkdir -p "$dname"
end
cp fs$i $i
end
end
