#!/bin/bash
set -o pipefail
for i in $(cat hosts | cut -f1 | grep -ve '^#' -e '^$'); do
echo '>>> ' Copying to $i
if ssh-copy-id $i 2>&1 | grep -Eie 'ERR|WARN'; then
echo '<<< ' Copying from $i
ssh $i 'ssh-copy-id (echo $SSH_CONNECTION | cut -d" " -f1)' 2>&1 | grep -Eie 'ERR|WARN'
fi
done
