#!/bin/bash
# TODO Rewrite this to recurse through ./fs/
mov() {
	cp -r $1 /$1
}
smov() {
	sudo cp -r $1 /$1
}

if [ ! -e ~/.ssh ]; then mkdir -p ~/.ssh; fi
if [ ! -e ~/.config ]; then mkdir -p ~/.config; fi
if [ ! -e ~/src/scripts ]; then mkdir -p ~/src/scripts; fi
if [ ! -e ~/tmp ]; then mkdir -p ~/tmp; fi

mov home/jtreed/.ssh/config
mov home/jtreed/.profile
mov home/jtreed/.config/fish
mov home/jtreed/.config/i3
mov home/jtreed/.xinitrc
mov home/jtreed/src/scripts/screenshot
smov etc/i3status.conf
