#!/bin/bash
echo Installing: git fish kitty netcat hub dmenu curl i3-wm i3blocks i3status i3lock xorg-xinit google-chrome net-tools xorg-xset xf86-drivers tmux
case $(uname -a) in
        *ebian*);&
        *buntu*) sudo apt install git fish kitty netcat hub dmenu curl net-tools xorg-xse xf86-drivers tmux;;
        *rch*) sudo pacman -S --noconfirm git;
                if [ ! -e /usr/bin/yay ]; then
                pushd ~/src;
                git clone https://aur.archlinux.org/yay.git;
                pushd yay;
                makepkg -si --noconfirm;
                popd;
                popd; fi
                yay -S --sudoloop --noconfirm --mflags --skipinteg fish kitty netcat hub dmenu curl windows10-icon-theme-git i3-wm i3blocks i3status i3lock xorg-xinit google-chrome net-tools tmux;;
esac
