#!/bin/fish
if [ -z "$argv[1]" ]

for i in (./checkdiff 2>/dev/null);
echo $i
./pull $i
end
else

set localpath fs$argv[1]
#echo path $localpath
set localdir (dirname $localpath)
#echo dir  $localdir

if [ ! -f $localdir ]
mkdir -p $localdir
end

#echo cp $argv[1] $localpath
if test -d $argv[1];
cp -r $argv[1]/* $localpath
else
cp $argv[1] $localpath
end
end
