#!/bin/fish
if [ -z "$argv[1]" ]

for i in (find ./fs -type f -exec echo {} \; | sed 's/\.\/fs//g');
echo ./pull $i
./pull $i
end
else

set localpath fs$argv[1]
#echo path $localpath
set localdir (dirname $localpath)
#echo dir  $localdir

if [ ! -f $localdir ]
mkdir -p $localdir
end

#echo cp $argv[1] $localpath
cp $argv[1] $localpath
end
