#!/usr/bin/fish
set battstat (upower -i /org/freedesktop/UPower/devices/battery_BAT0 | sed 's/^\s*/#/g' | grep -E "state|to\ full|percentage")
echo-notify 'Battery status' (echo $battstat | sed 's/#\s*//;s/\s*#\s*/; /g')
