#!/usr/bin/fish
set battstat (upower -i /org/freedesktop/UPower/devices/battery_BAT0 | sed 's/^\s*/#/g' | grep -E "state|to\ full|percentage" | tee /dev/stderr)
notify-send 'Battery status' (echo $battstat | sed 's/#\s*/\\\\n/g')
