#!/bin/bash

if [ -z "$2" ]; then
out=/dev/stdout
else
out=$2.$1
fi

case "$1" in
	"sh")	echo '#!/bin/sh' > $out;;
	"bash")	echo '#!/bin/bash' > $out;;
	"zsh")	echo '#!/usr/bin/zsh' > $out;;
	"fish")	echo '#!/usr/bin/fish' > $out;;
	"html")	cat << EOF > $out;;
<!doctype html>
<html lang="en">
<head>
	<title></title>
</head>
<body>
</body>
</html>
EOF
	"cpp")	cat << EOF > $out;;
#include <iostream>

using namespace std;

int main(int argc, char** argv) {
	
}
EOF
	"h")	upper=$(echo $2 | tr a-z A-Z); cat << EOF > $out;;
#ifndef ${upper}_H
#define ${upper}_H



#endif // ${upper}_H
EOF
esac

if [ ! -z "$2" ]; then # perform actions to prep files
case $1 in
	"sh")	;&
	"bash")	;&
	"zsh")	;&
	"fish")	chmod +x $out;;
esac
fi
