#!/bin/bash
#sudo sed -i 's/HandleLidSwitch=ignore/HandleLidSwitch=suspend/' /etc/systemd/logind.conf
sudo systemctl unmask sleep.target suspend.target hibernate.target hybrid-sleep.target && xset +dpms
