#!/bin/bash
sudo ip link set wlan0 down
case $1 in
	"")	sudo airodump-ng wlan0 --berlin 1 --ignore-negative-one;;
	*)	profile=$(ls /etc/netctl | fzf -f "$1" | head -n1)
		echo-notify "Switching to $profile"
		sudo netctl switch-to $profile
esac
